/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Mantenimiento;

import DAO.DAOCliente;
import DAO.DAOEmpleado;
import DAO.DAOProducto;
import DAO.DAOVentas;
import Entidades.Cliente;
import Entidades.DET_Venta;
import Entidades.Usuario;
import Entidades.Producto;
import Entidades.Venta;
import java.util.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reant
 */
public class MantVentas extends javax.swing.JFrame {

    private Venta nueva;
    /**
     * Creates new form MantVentas
     */
    public MantVentas() {
        initComponents();
        Actualizar_TablaVenta();
        CargarClientes();
        CargarEmpleados();
        CargarProductos();
        Bloqueo(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnNueva = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPaneDETV = new javax.swing.JScrollPane();
        JTableDETV = new javax.swing.JTable();
        btnAgregarDETVEN = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCANTIDAD = new javax.swing.JTextField();
        cbxProductos = new javax.swing.JComboBox<>();
        btnModificarDETV = new javax.swing.JButton();
        btnBorrarDETV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ventas");

        jLabel4.setText("Fecha(YY-MM-DD):");

        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });

        btnNueva.setText("Nueva Venta");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconRefresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        JTableDETV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneDETV.setViewportView(JTableDETV);

        btnAgregarDETVEN.setText("Agregar Producto a la Venta");
        btnAgregarDETVEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDETVENActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel7.setText("Producto:");

        jLabel8.setText("Cantidad:");

        txtCANTIDAD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCANTIDADKeyTyped(evt);
            }
        });

        btnModificarDETV.setText("Modificar compra");

        btnBorrarDETV.setText("Eliminar Compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(btnAgregarDETVEN))
                            .addComponent(cbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnModificarDETV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrarDETV)
                        .addGap(143, 143, 143)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPaneDETV, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNueva)
                    .addComponent(jLabel4)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarDETVEN))))
                .addGap(51, 51, 51)
                .addComponent(jScrollPaneDETV, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnBorrarDETV)
                    .addComponent(btnModificarDETV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        char c = evt.getKeyChar();
        if( (c<'0' || c>'9') && c!='-'){
            evt.consume();
        }
    }//GEN-LAST:event_txtFechaKeyTyped

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        // TODO add your handling code here:
        nueva = new Venta();
        Bloqueo(true);
        
    }//GEN-LAST:event_btnNuevaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        Actualizar_TablaVenta();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.nueva = null;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Numero de Venta");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio Neto");
        
        JTableDETV.setModel(modelo);
        Bloqueo(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarDETVENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDETVENActionPerformed
        DAOProducto daoP = new DAOProducto();
        Producto p = daoP.BuscarporNombre(cbxProductos.getSelectedItem().toString());
        int stoc = p.getStock();
        int cant = Integer.parseInt(txtCANTIDAD.getText());
        if( cant > stoc){
            JOptionPane.showMessageDialog(rootPane, "Cantidad exceciva");
        }else{
            p.setStock(stoc-cant);
            daoP.Editar(p);
            DET_Venta nuevo = new DET_Venta(p, cant);
            
            nueva.añadir_compra(nuevo);
        }
        Ver_DETVenta(nueva.getCompras());
    }//GEN-LAST:event_btnAgregarDETVENActionPerformed

    private void txtCANTIDADKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCANTIDADKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0' || c>'9'){
            evt.consume();
        }
    }//GEN-LAST:event_txtCANTIDADKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        DAOVentas dao = new DAOVentas();
        DAOCliente daoC = new DAOCliente();
        DAOEmpleado daoE = new DAOEmpleado();        
        
        String nombreC;
        int separador;
        int ID;
        
        nombreC = (String) this.cbxCliente.getSelectedItem();
        separador = nombreC.indexOf(" ");
        ID = Integer.parseInt( nombreC.substring(0,separador) );
        
        nueva.setCliente(daoC.BuscarporID(ID));
        
        nombreC = (String) this.cbxEmpleado.getSelectedItem();
        separador = nombreC.indexOf(" ");
        ID = Integer.parseInt( nombreC.substring(0,separador) );
        
        nueva.setEmpleado(daoE.BuscarporID(ID));
        nueva.setFechaE(txtFecha.getText());
        nueva.setNumVenta(dao.VerUltimoNumVenta() + 1);
        
        dao.Insertar(nueva);
        Bloqueo(false);
        Actualizar_TablaVenta();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantVentas().setVisible(true);
            }
        });
    }

    private void CargarClientes(){
        DAOCliente dao = new DAOCliente();
        List<Cliente> lista= dao.Listar();
        Iterator it = lista.iterator();
        while(it.hasNext()){
            Cliente aux = (Cliente) it.next();
            String item = aux.getIdCliente()+" - "+aux.getNombre()+" "+aux.getApellido();
            cbxCliente.addItem(item);
        }
    }
    private void CargarEmpleados(){
        DAOEmpleado dao = new DAOEmpleado();
        List<Usuario> lista = dao.Listar();
        Iterator it=lista.iterator();
        while(it.hasNext()){
            Usuario aux = (Usuario) it.next();
            String item = aux.getCodEmpleado()+" - "+aux.getNombre()+" "+aux.getApellido();
            cbxEmpleado.addItem(item);
        }
    }
    private void CargarProductos(){
        DAOProducto dao = new DAOProducto();
        List<Producto> list = dao.Listar();
        
        for(Producto tmp : list){
            cbxProductos.addItem(tmp.getDescripcion());
        }
    }
    private void Ver_DETVenta( List<DET_Venta> lista){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setRowCount(lista.size());
        modelo.addColumn("Producto");
        modelo.addColumn("Precio Unitario");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio Neto");
        
        Iterator it = lista.iterator();
        int i=0;
        while(it.hasNext()){
           DET_Venta tmp= (DET_Venta) it.next();
           modelo.setValueAt(tmp.getP().getDescripcion(), i, 0);
           modelo.setValueAt(tmp.getP().getPrecioUni(), i, 1);
           modelo.setValueAt(tmp.getCantidad(), i, 2);
           modelo.setValueAt(tmp.getPrecioN(), i, 3);
           i++;
        }
        this.JTableDETV.setModel(modelo);
    }
    private void Actualizar_TablaVenta(){
        DefaultTableModel modelo = new DefaultTableModel();
        DAOVentas dao = new DAOVentas();
        List<Venta> lista = dao.Listar();
        Iterator it=lista.iterator();
        
        modelo.setRowCount(lista.size());
        modelo.addColumn("Numero de Venta");
        modelo.addColumn("Fecha de Emision");
        modelo.addColumn("Precio Total");
        modelo.addColumn("Cliente");
        modelo.addColumn("Empleado");
        
        int i = 0;
        while(it.hasNext()){
            Venta aux = (Venta) it.next();
            Cliente c_tmp = aux.getCliente();
            Usuario e_tmp = aux.getEmpleado();
            
            modelo.setValueAt(aux.getNumVenta(), i, 0);
            modelo.setValueAt(aux.getFechaE(), i, 1);
            modelo.setValueAt(aux.getPrecioT(), i, 2);
            modelo.setValueAt(c_tmp.getNombre()+" "+c_tmp.getApellido(), i, 3);
            modelo.setValueAt(e_tmp.getNombre()+" "+e_tmp.getApellido(), i, 4);
            i++;
        }
        this.JTableVentas.setModel(modelo);
    }
    
    private void Bloqueo(boolean estado){
        cbxCliente.setEnabled(estado);
        cbxEmpleado.setEnabled(estado);
        txtFecha.setEnabled(estado);
        btnGuardar.setEnabled(estado);
        btnAgregarDETVEN.setEnabled(estado);
        btnCancelar.setEnabled(estado);
        this.txtCANTIDAD.setEnabled(estado);
        this.cbxProductos.setEnabled(estado);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableDETV;
    private javax.swing.JButton btnAgregarDETVEN;
    private javax.swing.JButton btnBorrarDETV;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificarDETV;
    private javax.swing.JButton btnNueva;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cbxProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPaneDETV;
    private javax.swing.JTextField txtCANTIDAD;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
